# Generated by Django 5.1.5 on 2025-01-23 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MutualFunds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('fund_type', models.CharField(choices=[('EQUITY', 'Equity'), ('DEBT', 'Debt'), ('HYBRID', 'Hybrid')], max_length=255)),
                ('nav', models.FloatField()),
            ],
        ),
    ]
